#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Regenerates lib/uts58/constants.rb from the UTS58 linkification data files
# published by Unicode:
#
#   ruby tools/maketables.rb > lib/uts58/constants.rb
#
# It fetches LinkBracket.txt (the Link_Bracket pairing) and LinkTerm.txt (the
# Link_Term property) for the version below. Link_Term is Hard for every code
# point not listed (UTS58 @missing default), so we emit only the
# Include/Soft/Open/Close ranges; the runtime treats anything uncovered as
# Hard. That keeps the table to ~2000 ranges instead of enumerating every
# letter.

require "open-uri"

VERSION = "17.0.0"
BASE = "https://www.unicode.org/Public/#{VERSION}/linkification"

def fetch(name)
  URI.open("#{BASE}/#{name}", &:read)
end

# Link_Bracket: "<close> ; <open> # name" → OPENERS[close] = open.
openers = []
fetch("LinkBracket.txt").each_line do |line|
  body, comment = line.split("#", 2)
  next unless (m = /\A\s*([0-9A-Fa-f]+)\s*;\s*([0-9A-Fa-f]+)/.match(body))
  openers << [m[1].to_i(16), m[2].to_i(16), comment.to_s.strip]
end
openers.sort_by! { |close, _open, _name| close }

# Link_Term: "<start>(..<end>) ; <Value> # name". Hard is the @missing default
# and need not be stored, so we drop it.
ranges = []
fetch("LinkTerm.txt").each_line do |line|
  body, comment = line.split("#", 2)
  next unless (m = /\A\s*([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*(\w+)/.match(body))
  value = m[3].downcase
  next if value == "hard"
  ranges << [m[1].to_i(16), (m[2] || m[1]).to_i(16), value, comment.to_s.strip]
end
ranges.sort_by! { |start, _e, _v, _n| start }

puts "# frozen_string_literal: true"
puts
puts "# Generated by tools/maketables.rb from the UTS58 #{VERSION} data files at"
puts "# #{BASE}/ . Do not edit by hand; rerun the generator."
puts "module Uts58"
puts "  module Constants"
puts "    # Link_Bracket: each closing bracket mapped to its opener."
puts "    OPENERS = {"
openers.each do |close, open, name|
  puts format("      0x%04X => 0x%04X, # %s", close, open, name)
end
puts "    }.freeze"
puts
puts "    # Link_Term values other than Hard, as [start, end, value] sorted by"
puts "    # start for binary search. A code point not covered here is Hard, the"
puts "    # UTS58 @missing default; see Uts58::Extractor#link_term."
puts "    LINK_TERM = ["
ranges.each do |start, e, value, name|
  puts format("      [0x%04X, 0x%04X, :%s], # %s", start, e, value, name)
end
puts "    ].freeze"
puts "  end"
puts "end"
