#!/usr/bin/env node
// Translates ../uts58/lib/uts58/constants.rb to src/constants.js,
// run-length encoding the TERMINATION table so the loaded module isn't
// 138k lines wide.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const rubyPath = process.argv[2] ||
  resolve(here, '..', '..', 'uts58', 'lib', 'uts58', 'constants.rb');
const outPath = resolve(here, '..', 'src', 'constants.js');

const src = readFileSync(rubyPath, 'utf8');

const openers = [];
const openerRe = /^\s*0x([0-9A-Fa-f]+)\s*=>\s*0x([0-9A-Fa-f]+),/;
const termRe = /^\s*0x([0-9A-Fa-f]+)\s*=>\s*:(\w+)\s*,/;

let inOpeners = false, inTerm = false;
const term = []; // array of {cp, kind}
for (const line of src.split('\n')) {
  if (line.includes('OPENERS = {')) { inOpeners = true; continue; }
  if (line.includes('TERMINATION = {')) { inOpeners = false; inTerm = true; continue; }
  if (inOpeners) {
    const m = openerRe.exec(line);
    if (m) openers.push([parseInt(m[1], 16), parseInt(m[2], 16)]);
  } else if (inTerm) {
    const m = termRe.exec(line);
    if (m) term.push({ cp: parseInt(m[1], 16), kind: m[2] });
  }
}

// run-length encode: array of [start, end, kindCode]
const kindCodes = { hard: 0, soft: 1, open: 2, close: 3 };
term.sort((a, b) => a.cp - b.cp);
const ranges = [];
for (const { cp, kind } of term) {
  const code = kindCodes[kind];
  if (code === undefined) throw new Error(`unknown kind ${kind}`);
  const last = ranges[ranges.length - 1];
  if (last && last[2] === code && last[1] === cp - 1) {
    last[1] = cp;
  } else {
    ranges.push([cp, cp, code]);
  }
}

const openerEntries = openers
  .map(([a, b]) => `  [0x${a.toString(16)}, 0x${b.toString(16)}],`)
  .join('\n');

// Two parallel typed arrays: starts and a packed end/kind value.
// end up to 0x10ffff fits in 21 bits, kind in 2 bits — pack together to halve the size.
const starts = new Uint32Array(ranges.length);
const packed = new Uint32Array(ranges.length); // (end << 2) | kind
for (let i = 0; i < ranges.length; i++) {
  starts[i] = ranges[i][0];
  packed[i] = (ranges[i][1] << 2) | ranges[i][2];
}

// emit as base64-encoded little-endian Uint32 arrays so the source file stays compact
function b64(u32) {
  const buf = Buffer.from(u32.buffer, u32.byteOffset, u32.byteLength);
  return buf.toString('base64');
}

const out = `// Generated by tools/maketables.js from the Ruby reference's constants.rb.
// Do not edit by hand; rerun the generator instead.

export const OPENERS = new Map([
${openerEntries}
]);

const KIND_HARD = 0, KIND_SOFT = 1, KIND_OPEN = 2, KIND_CLOSE = 3;
export const TERMINATION_KIND = Object.freeze({
  hard: KIND_HARD, soft: KIND_SOFT, open: KIND_OPEN, close: KIND_CLOSE,
});

const _startsB64 = ${JSON.stringify(b64(starts))};
const _packedB64 = ${JSON.stringify(b64(packed))};

function _decode(b64) {
  const bin = Buffer.from(b64, 'base64');
  return new Uint32Array(bin.buffer, bin.byteOffset, bin.byteLength / 4);
}

const STARTS = _decode(_startsB64);
const PACKED = _decode(_packedB64);

// Returns one of KIND_HARD/SOFT/OPEN/CLOSE for cp, or -1 if cp has no
// entry in the table. Binary search over a flat run-length encoding;
// the table is generated from constants.rb so the answers match the
// Ruby reference implementation.
export function terminationKind(cp) {
  let lo = 0, hi = STARTS.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >>> 1;
    const s = STARTS[mid];
    const p = PACKED[mid];
    const end = p >>> 2;
    if (cp < s) hi = mid - 1;
    else if (cp > end) lo = mid + 1;
    else return p & 3;
  }
  return -1;
}
`;

writeFileSync(outPath, out);
console.error(`wrote ${outPath}: ${ranges.length} ranges, ${openers.length} openers`);
