#!/usr/bin/env node
// Translates ../ruby/lib/uts58/constants.rb (OPENERS + the LINK_TERM ranges)
// to src/constants.js, packing the ranges so the loaded module stays small.
// Rerun this whenever the Ruby generator refreshes constants.rb.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const rubyPath = process.argv[2] ||
  resolve(here, '..', '..', 'ruby', 'lib', 'uts58', 'constants.rb');
const outPath = resolve(here, '..', 'src', 'constants.js');

const src = readFileSync(rubyPath, 'utf8');

const openers = [];
const openerRe = /^\s*0x([0-9A-Fa-f]+)\s*=>\s*0x([0-9A-Fa-f]+),/;
// LINK_TERM rows look like: [0x0021, 0x0022, :soft], # comment
const termRe = /^\s*\[0x([0-9A-Fa-f]+),\s*0x([0-9A-Fa-f]+),\s*:(\w+)\]/;

let inOpeners = false, inTerm = false;
const parsed = []; // array of [start, end, kind]
for (const line of src.split('\n')) {
  if (line.includes('OPENERS = {')) { inOpeners = true; inTerm = false; continue; }
  if (line.includes('LINK_TERM = [')) { inOpeners = false; inTerm = true; continue; }
  if (inOpeners) {
    const m = openerRe.exec(line);
    if (m) openers.push([parseInt(m[1], 16), parseInt(m[2], 16)]);
  } else if (inTerm) {
    const m = termRe.exec(line);
    if (m) parsed.push([parseInt(m[1], 16), parseInt(m[2], 16), m[3]]);
  }
}

// The kinds are the non-Hard Link_Term values; an uncovered code point is
// Hard (handled at runtime by terminationKind returning -1). Pack into 2 bits.
const kindCodes = { include: 0, soft: 1, open: 2, close: 3 };
parsed.sort((a, b) => a[0] - b[0]);
const ranges = [];
for (const [start, end, kind] of parsed) {
  const code = kindCodes[kind];
  if (code === undefined) throw new Error(`unknown kind ${kind}`);
  const last = ranges[ranges.length - 1];
  if (last && last[2] === code && last[1] === start - 1) {
    last[1] = end;
  } else {
    ranges.push([start, end, code]);
  }
}

const openerEntries = openers
  .map(([a, b]) => `  [0x${a.toString(16)}, 0x${b.toString(16)}],`)
  .join('\n');

// Two parallel typed arrays: starts and a packed end/kind value.
// end up to 0x10ffff fits in 21 bits, kind in 2 bits — pack together to halve the size.
const starts = new Uint32Array(ranges.length);
const packed = new Uint32Array(ranges.length); // (end << 2) | kind
for (let i = 0; i < ranges.length; i++) {
  starts[i] = ranges[i][0];
  packed[i] = (ranges[i][1] << 2) | ranges[i][2];
}

// emit as base64-encoded little-endian Uint32 arrays so the source file stays compact
function b64(u32) {
  const buf = Buffer.from(u32.buffer, u32.byteOffset, u32.byteLength);
  return buf.toString('base64');
}

const out = `// Generated by tools/maketables.js from the Ruby reference's constants.rb.
// Do not edit by hand; rerun the generator instead.

export const OPENERS = new Map([
${openerEntries}
]);

const KIND_INCLUDE = 0, KIND_SOFT = 1, KIND_OPEN = 2, KIND_CLOSE = 3;
export const TERMINATION_KIND = Object.freeze({
  include: KIND_INCLUDE, soft: KIND_SOFT, open: KIND_OPEN, close: KIND_CLOSE,
});

const _startsB64 = ${JSON.stringify(b64(starts))};
const _packedB64 = ${JSON.stringify(b64(packed))};

function _decode(b64) {
  const bin = Buffer.from(b64, 'base64');
  return new Uint32Array(bin.buffer, bin.byteOffset, bin.byteLength / 4);
}

const STARTS = _decode(_startsB64);
const PACKED = _decode(_packedB64);

// Returns one of KIND_INCLUDE/SOFT/OPEN/CLOSE for cp, or -1 when cp has no
// entry — which means Hard, the UTS58 @missing default. Binary search over a
// flat run-length encoding; generated from constants.rb so the answers match
// the Ruby reference implementation.
export function terminationKind(cp) {
  let lo = 0, hi = STARTS.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >>> 1;
    const s = STARTS[mid];
    const p = PACKED[mid];
    const end = p >>> 2;
    if (cp < s) hi = mid - 1;
    else if (cp > end) lo = mid + 1;
    else return p & 3;
  }
  return -1;
}
`;

writeFileSync(outPath, out);
console.error(`wrote ${outPath}: ${ranges.length} ranges, ${openers.length} openers`);
