#!/usr/bin/env node
// Generates src/tlds-iana.js and src/suffixes-psl.js — the two public-suffix
// tables the extractor checks hosts against. Run with no arguments to fetch
// the canonical sources, or pass local paths to regenerate offline:
//
//   npm run maketlds
//   npm run maketlds -- /path/to/tlds-alpha-by-domain.txt /path/to/public_suffix_list.dat
//
// The IANA table is the root-zone TLD list as-is. The PSL table is the
// ICANN section only (we run with private domains off), folded for
// *plausibility*: '!' exceptions are dropped and '*.foo' wildcards collapse
// to their parent 'foo', because the extractor only asks "is this a
// plausible link", not "where is the exact registrable boundary". Both sets
// are A-label folded so the runtime check can stay ASCII.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import punycode from 'punycode/punycode.js';

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = resolve(here, '..', 'src');

const IANA_URL = 'https://data.iana.org/TLD/tlds-alpha-by-domain.txt';
const PSL_URL = 'https://publicsuffix.org/list/public_suffix_list.dat';

async function load(src) {
  if (/^https?:/.test(src)) {
    const r = await fetch(src);
    if (!r.ok) throw new Error(`fetch ${src}: ${r.status}`);
    return r.text();
  }
  return readFileSync(src, 'utf8');
}

function toAscii(label) {
  try {
    return punycode.toASCII(label).toLowerCase();
  } catch {
    return label.toLowerCase();
  }
}

function parseIana(text) {
  return text
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith('#'))
    .map((l) => l.toLowerCase());
}

function parsePsl(text) {
  const all = new Set();
  let inPrivate = false;
  for (const line of text.split('\n')) {
    if (line.startsWith('// ===BEGIN PRIVATE DOMAINS===')) inPrivate = true;
    if (inPrivate) continue;
    let t = line.trim();
    if (!t || t.startsWith('//')) continue;
    if (t.startsWith('!')) continue; // exception rule: irrelevant to plausibility
    if (t.startsWith('*.')) t = t.slice(2); // wildcard → its parent suffix
    all.add(toAscii(t));
  }

  // Keep only minimal suffixes. The runtime check accepts a host when any
  // trailing run of its labels is in the set, so a suffix whose own shorter
  // tail is already present can never change an answer: with 'no' in the
  // set, 'møre-og-romsdal.no' adds no value. This collapses most of the PSL.
  return [...all].filter((s) => {
    const labels = s.split('.');
    for (let i = 1; i < labels.length; i++) {
      if (all.has(labels.slice(i).join('.'))) return false;
    }
    return true;
  });
}

// A flat run-length-free module: the entries joined by spaces and split at
// load. Cheaper in bytes than a quoted-array literal, and gzips a touch
// smaller too.
function emit(varName, checkerNote, entries) {
  const sorted = [...entries].sort();
  return `// Generated by tools/maketlds.js. Do not edit by hand; rerun the generator.
// ${checkerNote}
import { makeHostChecker } from './plausible.js';

const ${varName} = new Set(
  ${JSON.stringify(sorted.join(' '))}.split(' '),
);

export const isPlausibleHost = makeHostChecker(${varName});
`;
}

const ianaSrc = process.argv[2] || IANA_URL;
const pslSrc = process.argv[3] || PSL_URL;

const iana = parseIana(await load(ianaSrc));
const psl = parsePsl(await load(pslSrc));

writeFileSync(
  resolve(srcDir, 'tlds-iana.js'),
  emit('TLDS', 'IANA root-zone TLDs: the rightmost label must be a real TLD.', iana),
);
writeFileSync(
  resolve(srcDir, 'suffixes-psl.js'),
  emit('SUFFIXES', 'Public Suffix List, ICANN section, folded for plausibility.', psl),
);

console.error(`wrote src/tlds-iana.js: ${iana.length} TLDs`);
console.error(`wrote src/suffixes-psl.js: ${psl.length} suffixes`);
